name: tcc
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - ipython
  - python=3.12
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - ruff
  - numpy>2
  - pandas
  - transformers
  - conda-forge::jaxtyping
  - conda-forge::beartype
  - matplotlib
  - pip
  - pip:
    - opencv-python
