[tool.pyright]

include = ["src"]
exclude = ["**/__pycache__"]

typeCheckingMode = "standard"
strictListInference = true
strictDictionaryInference = true
reportMissingTypeStubs = "none"

ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }

reportMissingImports = "error"

pythonVersion = "3.12"
pythonPlatform = "Linux"

[tool.ruff]

select = ["ALL"]
ignore = ["F722", "D100", "D101", "D102", "D103", "D104", "D105", "D107", "PGH003", "W293", "FA102"]
line-length = 100
